# This file is a template for Codemagic (codemagic.io) to automate building your game.
# You connect your GitHub repo to Codemagic, and it will use this file to build your app.
# Sensitive information like your signing keys should be stored as encrypted
# environment variables in the Codemagic UI, not here.

workflows:
  # === ANDROID WORKFLOW ===
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m1
    environment:
      node: 20
      groups:
        - keystore_credentials # Add your keystore info as a group in Codemagic UI
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync web assets to native project
        script: |
          npx cap sync android
      - name: Build Android App Bundle
        script: |
          set -x
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS # Stored in Codemagic UI
        track: internal # or alpha, beta, production

  # === IOS WORKFLOW ===
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    environment:
      node: 20
      xcode: latest
      groups:
        - app_store_credentials # Add your Apple Developer Portal info here in Codemagic
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Setup iOS keychain and code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$APP_STORE_CONNECT_ISSUER_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build web assets
        script: |
          npm run build
      - name: Sync web assets to native project
        script: |
          npx cap sync ios
      - name: Build iOS App
        script: |
          set -x
          xcode-project build-ipa --workspace "ios/App/App.xcworkspace" --scheme "App"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth:
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          key_id: $APP_STORE_CONNECT_KEY_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
        beta_groups: # optional, add groups from App Store Connect
          - "Testers"
